# To change this template, choose Tools | Templates
# and open the template in the editor.
#local
driver=org.postgresql.Driver
#server kantor
#user=x1BoaoIISFobwxuB9Ihg2g==
#password=x1BoaoIISFobwxuB9Ihg2g==

#local
url=jdbc:postgresql://localhost:5432/DBCM-DANAMON
#user=postgres
#password=admin
user=x1BoaoIISFobwxuB9Ihg2g==
password=hqsFoZe0ylA=

##local
outgoing_dir=C:/Users/HP/Documents/Vensys/Bank-Mega/App/folder-reader/frontend/outgoing
incoming_dir=C:/Users/HP/Documents/Vensys/Bank-Mega/App/folder-reader/backend/incoming
