# To change this template, choose Tools | Templates
# and open the template in the editor.
#local
driver=org.postgresql.Driver
url=jdbc:postgresql://192.168.220.42:5432/DBCM-DANAMON

#server kantor
#user=x1BoaoIISFobwxuB9Ihg2g==
#password=x1BoaoIISFobwxuB9Ihg2g==

#local
#user=postgres
#password=admin
user=x1BoaoIISFobwxuB9Ihg2g==
password=hqsFoZe0ylA=

##local
outgoing_dir=C:/Users/HP/Documents/Vensys/Bank-Mega/App/folder-reader/frontend/outgoing
dirFrontEndOutgoingMX=D:/Interface/Frontend/outgoing_mx
incoming_dir=C:/Users/HP/Documents/Vensys/Bank-Mega/App/folder-reader/backend/incoming
